### PR TITLE
Added most basic Dockerfile.

### PR DESCRIPTION
**Pull request by Jan-M**
I setup a test Excalidraw on K8s and just want to share this most basic Dockerfile for Js beginners like me.

I got the following setup nicely working:
 * excalidraw (internal service)
 * excalidraw-room (internal service)
 * oauth2-proxy with Google Auth ingress (with two downstreams)

Will see how/where to share the K8s deployments manifests if interest exists.

Great project/work.

### CODE REVIEW

**Comment by NMinhNguyen** [comment]
Sorry, just noticed this PR when I raised mine (#71). There's a few ways in which my PR differs:

- uses Yarn and `yarn.lock` which is version controlled in this repo
- leverages cached Docker layers: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
- avoids global installation of scripts (e.g. `typescript`)

**Comment by Jan-M** [comment]
Yes using a smaller base image is for sure appreciated.

I did this with very limited JS knowledge in terms of how to do this properly, but also did not want to hide it in case someone else needed it.

So now that there is an alternative I am happy to close this.

Thanks!

**Comment by NMinhNguyen** [comment]
I'm also happy for you to cherry-pick the changes from my PR and apply them here because you were first 🙂

**Comment by Jan-M** [comment]
Closing this in favor of #71

**Comment by NMinhNguyen** [comment]
> oauth2-proxy with Google Auth ingress (with two downstreams)

Could you elaborate on this btw? Did you end up using https://github.com/excalidraw/excalidraw-json with its dependency on Google Cloud?

**Comment by Jan-M** [comment]
I am referring to this, deploying two services, excalidraw and the room service as separate deployments and services.

https://github.com/Jan-M/excalidraw-k8s-demo/blob/master/deploy-oauth2-proxy.yaml#L57

I have not yet added your JSON backend, which is appreciated as I do not use Google services (outside the auth part), K8s backed by AWS EC2.

To me it is not yet clear what the JSON backend brings me and how to configure this in excalidraw Docker image.

**Comment by NMinhNguyen** [comment]
> To me it is not yet clear what the JSON backend brings me and how to configure this in excalidraw Docker image.

The ability to generate (and store) shareable links. You should be able to use any S3-compatible storage including Amazon S3 or https://min.io/ (configured via environment variables).

**Comment by Jan-M** [comment]
Is there a way to configure the endpoint similar to `REACT_APP_SOCKET_SERVER_URL`?

Maybe time to look into a doc pr.

**Comment by NMinhNguyen** [comment]
> Is there a way to configure the endpoint similar to `REACT_APP_SOCKET_SERVER_URL`?

Yup, check out https://github.com/excalidraw/excalidraw/blob/bac20fa6418efd7b9eebcfd54b89e46bfed1ac7c/.env#L1-L3

> Maybe time to look into a doc pr.

I think docs can be added once `excalidraw` Docker image can be fully configured via environment variables (https://github.com/excalidraw/excalidraw/issues/1772). Currently you'd need to `git clone` and build the repo yourself, but I guess it is somewhat workable already?

**Comment by Jan-M** [comment]
Would changing those be good enough, is that whats "hidding" the json backend?

`REACT_APP_BACKEND_V2_GET_URL`
`REACT_APP_BACKEND_V2_POST_URL`

**Comment by NMinhNguyen** [comment]
> Would changing those be good enough, is that whats "hidding" the json backend?

Yup. Although bear in mind that there's a small issue with the provided Docker image right now - I introduced a small bug when I refactored environment variables but there's a PR up for that now https://github.com/excalidraw/excalidraw/pull/1922

**Pull request closed without merging**
